name: QitOps CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt, clippy
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
    
    - name: Check formatting
      run: cargo fmt -- --check
    
    - name: Clippy
      run: cargo clippy -- -D warnings
    
    - name: Build
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose
    
    - name: Run API tests
      run: cargo run -- api -c tests/configs/api_test.json
    
    - name: Run Performance tests
      run: cargo run -- performance -c tests/configs/performance_test.json -u 5 -d 10
    
    - name: Run Security tests
      run: cargo run -- security -c tests/configs/security_test.json -d 1 -p
    
    - name: Run Web tests
      run: cargo run -- web -c tests/configs/web_test.json

  release:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    - name: Build release
      run: cargo build --release
    
    - name: Create release artifact
      run: |
        mkdir -p release
        cp target/release/qitops release/
        cp -r tests/configs release/
        tar -czf qitops-release.tar.gz release/
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: qitops-release
        path: qitops-release.tar.gz
